language: node_js

os: windows

node_js:
  - node

cache:
  directories:
    - 'node_modules'

install:
  - npm install

addons:
  postgresql: '15.0'
  apt:
    packages:
      - postgresql-15.0

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - PGHOST=localhost

before_script:
  - psql -c 'create database teamwork;' -U postgres
  - psql -c 'CREATE USER ebube WITH PASSWORD null;' -U postgres

script:
  - npm test

after_success:
  - npm run coverage
