language: node_js

os: windows

node_js:
  - node

cache:
  directories:
    - 'node_modules'

install:
  - npm install

services:
  - postgresql

env:
  global:
    - NODE_ENV=test

script:
  - npm test

after_success:
  - npm run coverage
