language: node_js

os: windows

node_js:
  - node

cache:
  directories:
    - 'node_modules'

install:
  - npm install

services:
  - postgresql

addons:
  postgresql: '15'
  apt:
    packages:
      - postgresql-15
      - postgresql-client-15
env:
  global:
    - PGPORT=5433
    - PGUSER=travis
    - NODE_ENV=test

before_script:
  - psql -c 'CREATE DATABASE teamwork;' -U postgres
  - psql -c 'CREATE USER ebube WITH PASSWORD null;' -U postgres

script:
  - npm test

after_success:
  - npm run coverage
